name: Build and Test .NET Project
 
on:
    push:
      branches:
        - main    # Замените на вашу ветку, например, main или master
 
jobs:
    build:
      runs-on: ubuntu-latest
 
      steps:
      - name: Checkout repository
        uses: actions/checkout@v3
 
      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '7.x'    # Замените на нужную версию .NET
 
      - name: Build project
        run: dotnet build WizardsoftApi.csproj --configuration Release
 
      - name: Run tests (фиктивно)
        run: echo "Выполняем фиктивные тесты..."
 
      - name: Copy compiled code to client (фиктивно)
        run: echo "Копируем скомпилированный код воображаемому клиенту..."
 
      - name: Publish to Nexus (фиктивно)
        run: echo "Публикуем воображаемые библиотеки в воображаемый Nexus..."
 
      - name: Send email on success
        if: success()
        uses: dawidd6/action-sendmail@v3
        with:
          server_address: smtp.example.com    # Замените на адрес вашего SMTP-сервера
          server_port: 587    # Порт SMTP-сервера
          username: ${{ secrets.EMAIL_USERNAME }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          subject: "Успешное завершение пайплайна"
          body: "Пайплайн успешно завершен. Все задачи выполнены успешно."
          sender: ${{ secrets.EMAIL_SENDER }}
          recipients: recipient@example.com    # Замените на адрес получателя
 
      - name: Send email on failure
        if: failure()
        uses: dawidd6/action-sendmail@v3
        with:
          server_address: smtp.example.com    # Замените на адрес вашего SMTP-сервера
          server_port: 587    # Порт SMTP-сервера
          username: ${{ secrets.EMAIL_USERNAME }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          subject: "Ошибка в пайплайне"
          body: "Пайплайн завершился с ошибкой. Пожалуйста, проверьте логи."
          sender: ${{ secrets.EMAIL_SENDER }}
          recipients: recipient@example.com    # Замените на адрес получателя
