name: Build and Test .NET Project
 
on:
    push:
      branches:
        - master    # Замените на вашу ветку, например, main или master
 
jobs:
    build:
      runs-on: ubuntu-latest
 
      steps:
      - name: Checkout repository
        uses: actions/checkout@v3
 
      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '7.x'    # Замените на нужную версию .NET
 
      - name: Build project
        run: dotnet build WizardsoftApi.csproj --configuration Release
 
      - name: Run tests (фиктивно)
        run: dotnet test test1.csproj
 
      - name: Copy compiled code to client (фиктивно)
        run: echo "Копируем скомпилированный код воображаемому клиенту..."
 
      - name: Publish to Nexus (фиктивно)
        run: curl app1.dll http//:localhost:8081/
		echo "Публикуем воображаемые библиотеки в воображаемый Nexus..."
